// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type InfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Version info.
	VersionInfo *components.VersionInfo
}

func (o *InfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *InfoResponse) GetVersionInfo() *components.VersionInfo {
	if o == nil {
		return nil
	}
	return o.VersionInfo
}
