// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ConnectedOuterService struct {
	Name    *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
}

func (o *ConnectedOuterService) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ConnectedOuterService) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}
