// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Schema struct {
}

// SchemaRequest - Represents a model to Schema Request
type SchemaRequest struct {
	// Represents a model to Schema Info including status, creation and schemaIdentity
	SchemaInfo SchemaInfo `json:"schemaInfo"`
	Schema     Schema     `json:"schema"`
}

func (o *SchemaRequest) GetSchemaInfo() SchemaInfo {
	if o == nil {
		return SchemaInfo{}
	}
	return o.SchemaInfo
}

func (o *SchemaRequest) GetSchema() Schema {
	if o == nil {
		return Schema{}
	}
	return o.Schema
}
