// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SchemaInfoResponse - The response for a GET schema request
type SchemaInfoResponse struct {
	SchemaInfos []SchemaInfo
	// The offset for the next query
	Offset *int
	// The number of schema versions in this response
	Count *int
	// The total number of entity type codes in the repositories
	TotalCount *int
}

func (o *SchemaInfoResponse) GetSchemaInfos() []SchemaInfo {
	if o == nil {
		return nil
	}
	return o.SchemaInfos
}

func (o *SchemaInfoResponse) GetOffset() *int {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *SchemaInfoResponse) GetCount() *int {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *SchemaInfoResponse) GetTotalCount() *int {
	if o == nil {
		return nil
	}
	return o.TotalCount
}
