// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SchemaIdentity - Schema authority source and type description
type SchemaIdentity struct {
	// Entity authority
	Authority string `json:"authority"`
	// Entity source
	Source string `json:"source"`
	// EntityType Code
	EntityType string `json:"entityType"`
	// Major Schema Version Number
	SchemaVersionMajor int64 `json:"schemaVersionMajor"`
	// Minor Schema Version Number
	SchemaVersionMinor int64 `json:"schemaVersionMinor"`
	// Patch Schema Version Number
	SchemaVersionPatch int64 `json:"schemaVersionPatch"`
	// A read-only system defined id used for referencing of a schema.
	ID *string `json:"id,omitempty"`
}

func (o *SchemaIdentity) GetAuthority() string {
	if o == nil {
		return ""
	}
	return o.Authority
}

func (o *SchemaIdentity) GetSource() string {
	if o == nil {
		return ""
	}
	return o.Source
}

func (o *SchemaIdentity) GetEntityType() string {
	if o == nil {
		return ""
	}
	return o.EntityType
}

func (o *SchemaIdentity) GetSchemaVersionMajor() int64 {
	if o == nil {
		return 0
	}
	return o.SchemaVersionMajor
}

func (o *SchemaIdentity) GetSchemaVersionMinor() int64 {
	if o == nil {
		return 0
	}
	return o.SchemaVersionMinor
}

func (o *SchemaIdentity) GetSchemaVersionPatch() int64 {
	if o == nil {
		return 0
	}
	return o.SchemaVersionPatch
}

func (o *SchemaIdentity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}
