// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	Authorization string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *Security) GetAuthorization() string {
	if o == nil {
		return ""
	}
	return o.Authorization
}
