// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type VersionInfo struct {
	GroupID                *string                 `json:"groupId,omitempty"`
	ArtifactID             *string                 `json:"artifactId,omitempty"`
	Version                *string                 `json:"version,omitempty"`
	BuildTime              *string                 `json:"buildTime,omitempty"`
	Branch                 *string                 `json:"branch,omitempty"`
	CommitID               *string                 `json:"commitId,omitempty"`
	CommitMessage          *string                 `json:"commitMessage,omitempty"`
	ConnectedOuterServices []ConnectedOuterService `json:"connectedOuterServices,omitempty"`
}

func (o *VersionInfo) GetGroupID() *string {
	if o == nil {
		return nil
	}
	return o.GroupID
}

func (o *VersionInfo) GetArtifactID() *string {
	if o == nil {
		return nil
	}
	return o.ArtifactID
}

func (o *VersionInfo) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *VersionInfo) GetBuildTime() *string {
	if o == nil {
		return nil
	}
	return o.BuildTime
}

func (o *VersionInfo) GetBranch() *string {
	if o == nil {
		return nil
	}
	return o.Branch
}

func (o *VersionInfo) GetCommitID() *string {
	if o == nil {
		return nil
	}
	return o.CommitID
}

func (o *VersionInfo) GetCommitMessage() *string {
	if o == nil {
		return nil
	}
	return o.CommitMessage
}

func (o *VersionInfo) GetConnectedOuterServices() []ConnectedOuterService {
	if o == nil {
		return nil
	}
	return o.ConnectedOuterServices
}
